In [2]:
%pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
print(pd.__version__)

3.0.6

In [4]:
try:
    import pandas as pd
    print("Pandas is installed. Version:", pd.__version__)
    # raise PandasException("This is a custom exception for demonstration purposes.")
except ValueError:
    print("Pandas is not installed. Please install it using 'pip install pandas'.")
except ModuleNotFoundError:
    print("Pandas is not installed. Please install it using 'pip install pandas'.")
except ImportError:
    print("Pandas is not installed. Please install it using 'pip install pandas'.")
except Exception as e:
    print("An error occurred while importing pandas:", str(e))

Pandas is installed. Version: 3.0.6

In [5]:
class PandasException(Exception):
    """Custom exception for Pandas-related errors."""
    def __init__(self, message):
        super().__init__(message)
        self.message = "PandasException: " + message

In [6]:
try:
    import pandas as pd
    print("Pandas is installed. Version:", pd.__version__)
except PandasException as e:
    print(e.message)

Pandas is installed. Version: 3.0.6

In [7]:
df_weather = pd.DataFrame({'City': ['New York', 'Los Angeles', 'Chicago'],
                           'Temperature': [30, 25, 20],
                           'Humidity': [70, 60, 80], 'Date': ['2023-01-01', '2023-01-02', '2023-01-03']})
df_weather

          City  Temperature  Humidity        Date
0     New York           30        70  2023-01-01
1  Los Angeles           25        60  2023-01-02
2      Chicago           20        80  2023-01-03

In [8]:
df_weather.transpose()

                      0            1           2
City           New York  Los Angeles     Chicago
Temperature          30           25          20
Humidity             70           60          80
Date         2023-01-01   2023-01-02  2023-01-03

In [9]:
new_row = {"City": "New York", "Temperature": 40, "Humidity": 60, "Date": "2024-01-01"}

new_row = {"City": "New York", "Temperature": 32, "Humidity": 60, "Date": "2024-01-02"}
df_weather.loc[len(df_weather)] = new_row
df_weather['year'] = pd.to_datetime(df_weather['Date']).dt.year
df_weather

          City  Temperature  Humidity        Date  year
0     New York           30        70  2023-01-01  2023
1  Los Angeles           25        60  2023-01-02  2023
2      Chicago           20        80  2023-01-03  2023
3     New York           32        60  2024-01-02  2024

In [10]:

df_weather.pivot_table(index='City', columns='year', values='Temperature', aggfunc='mean')

year         2023  2024
City
Chicago      20.0   NaN
Los Angeles  25.0   NaN
New York     30.0  32.0

In [12]:
df_weather.melt(id_vars=['City','year'],value_vars=['Temperature','Humidity'],var_name='Measurement',value_name='Value')

          City  year  Measurement  Value
0     New York  2023  Temperature     30
1  Los Angeles  2023  Temperature     25
2      Chicago  2023  Temperature     20
3     New York  2024  Temperature     32
4     New York  2023     Humidity     70
5  Los Angeles  2023     Humidity     60
6      Chicago  2023     Humidity     80
7     New York  2024     Humidity     60

In [13]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 
                   'Age': [4, 5, 6],
                    'Salary': [50000, 60000, None],
  'Department': [1, 2, 3],
  'Manager':[None, 'John', None],
   'skills': [['Python', 'SQL'], ['Java', 'C++'], None]})

df_new = df[(df['Age'] > 4) & (df['Salary'] < 70000)]
df_new

  Name  Age   Salary  Department Manager       skills
1  Bob    5  60000.0           2    John  [Java, C++]

In [14]:
df.isna()

    Name    Age  Salary  Department  Manager  skills
0  False  False   False       False     True   False
1  False  False   False       False    False   False
2  False  False    True       False     True    True

In [15]:
df.fillna({'Manager': 'Unknown'}, inplace=True)

      Name  Age   Salary  Department  Manager         skills
0    Alice    4  50000.0           1  Unknown  [Python, SQL]
1      Bob    5  60000.0           2     John    [Java, C++]
2  Charlie    6      NaN           3  Unknown           None

In [16]:
df.fillna({'Salary': df['Salary'].mean()}, inplace=True)

      Name  Age   Salary  Department  Manager         skills
0    Alice    4  50000.0           1  Unknown  [Python, SQL]
1      Bob    5  60000.0           2     John    [Java, C++]
2  Charlie    6  55000.0           3  Unknown           None

In [17]:
df.dropna(subset=['Salary'], inplace=True)
df

      Name  Age   Salary  Department  Manager         skills
0    Alice    4  50000.0           1  Unknown  [Python, SQL]
1      Bob    5  60000.0           2     John    [Java, C++]
2  Charlie    6  55000.0           3  Unknown           None

In [18]:
df.dropna()

    Name  Age   Salary  Department  Manager         skills
0  Alice    4  50000.0           1  Unknown  [Python, SQL]
1    Bob    5  60000.0           2     John    [Java, C++]

In [19]:
department_df = pd.DataFrame({"id": [1, 2, 3, 4],
                              "department_name": ["HR", "IT", "Finance", "Technical"]})

In [20]:
df_merged = pd.merge(df, department_df, 
                     left_on='Department', 
                     right_on='id', how='outer')
df_merged

,Name,Age,Salary,Department,Manager,skills,id,department_name
0,Alice,4.0,50000.0,1.0,Unknown,"[Python, SQL]",1,HR
1,Bob,5.0,60000.0,2.0,John,"[Java, C++]",2,IT
2,Charlie,6.0,55000.0,3.0,Unknown,None,3,Finance
3,NaN,NaN,NaN,NaN,NaN,NaN,4,Technical

In [21]:
df_additional = pd.DataFrame({'Name': ['ABC', 'PQR', 'XYZ'], 
                   'Age': [14, 15, 16],
                    'Salary': [None, 60000, 40000],
  'Department': [4, 2, 1],
  'Manager':['Alice', 'Bob', 'Charlie'],
   'skills': [['Python', 'SQL'], ['Java', 'C++'], None]})

In [22]:
df_new = pd.concat([df, df_additional], ignore_index=True)
df_new

      Name  Age   Salary  Department  Manager         skills
0    Alice    4  50000.0           1  Unknown  [Python, SQL]
1      Bob    5  60000.0           2     John    [Java, C++]
2  Charlie    6  55000.0           3  Unknown           None
3      ABC   14      NaN           4    Alice  [Python, SQL]
4      PQR   15  60000.0           2      Bob    [Java, C++]
5      XYZ   16  40000.0           1  Charlie           None

In [25]:
new_df=df.copy()

In [40]:
new_df = df_additional.groupby('Department')['Salary'].mean().reset_index()

In [41]:
new_df.rename(columns={'Salary': 'Average_Salary'}, inplace=True)

In [43]:
new_df.dropna()

   Department  Average_Salary
0           1         40000.0
1           2         60000.0

In [45]:
new_df['Average_Salary'] = new_df['Average_Salary'].fillna(
    new_df['Average_Salary'].mean()
)

In [46]:
print(new_df)

   Department  Average_Salary
0           1         40000.0
1           2         60000.0
2           4         50000.0

In [49]:
new_df.filter(new_df['Average_Salary']> 500000.0)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [52]:
new_df.pipesort_values(by='Average_Salary',ascending=False)
new_df.pipe(
    lambda x: x.sort_values(by='Average_Salary', ascending=False)
)

AttributeError: 'DataFrame' object has no attribute 'pipesort_values'